# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"format_date": "00_parser.ipynb",
         "parse_query": "00_parser.ipynb"}

modules = ["parser.py"]

doc_url = "https://wragge.github.io/trove_query_parser/"

git_url = "https://github.com/wragge/trove_query_parser/tree/master/"

def custom_doc_links(name): return None
